### ISSUE TITLE
npm install 执行失败，为什么需python环境呢

### ISSUE THREAD

**Issue by JIAOBANTANG** [hadardb/webpack4-morePages-Layui#20]
npm ERR! code 1
npm ERR! path C:\Work\Code\morePages-Layui\node_modules\canvas
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.4.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Work\Code\morePages-Layui\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Work\Code\morePages-Layui\node_modules\node-gyp\lib\configure.js:509:16)npm ERR! gyp ERR! stack     at callback (C:\Work\Code\morePages-Layui\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Work\\Code\\morePages-Layui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Work\Code\morePages-Layui\node_modules\canvas
npm ERR! gyp ERR! node -v v16.4.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:

**Comment by hadardb** [comment]
具体我也不太清楚，你用 yarn试一下
